### ISSUE TITLE
[Vision API] CancelationToken for Async calls.

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Vision-Windows#2]
_From @snap608 on April 6, 2016 19:49_

Since the VisionServiceClient (C#) have no timeout we should be able to pass a CancelationToken or set a timeout for all calls to the API via the VisionServiceClient.

_PS: Because of the downtime today (6.apr 2016) our integration encountered a hang._

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#46_

**Comment by margaretmz** [comment]
_From @cthrash on April 9, 2016 0:15_

This will be considered in a future release.  The request will have timed out eventually on the client side(100 seconds).

**Comment by cthrash** [comment]
This client SDK is being deprecated in favor of our [new package](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Vision.ComputerVision).  This SDK support CancelationTokens.
