### ISSUE TITLE
How to retrieve landmarks

### ISSUE THREAD

**Issue by marcominerva** [Microsoft/Cognitive-Vision-Windows#21]
On the page https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision, there is a section telling that Vision API is able to recognize landmarks, and an example regarding Colosseum is provided:
![colosseum](https://user-images.githubusercontent.com/3522534/27594752-f6cf8790-5b5a-11e7-9112-012e538b8eca.png)

However, if I try to call the Vision API using an URL like the following one, with the same image in the body:

POST https://westcentralus.api.cognitive.microsoft.com/vision/v1.0/analyze?visualFeatures=Categories&language=en&subscription-key=<my_subscription_key>

I obtain this:

![fiddler](https://user-images.githubusercontent.com/3522534/27594907-6dd23e5a-5b5b-11e7-8e0f-de191b697682.png)

So, the categories are the same, but with no detail. Am I missing something in order to retrieve landmarks information?

**Comment by marcominerva** [comment]
Never mind, using the testing console I have found the issue: I need to insert the _details_ query string parameter.

**Comment by cthrash** [comment]
Note also that if you only care about landmarks, you can call `/vision/v1.0/models/landmarks/analyze' API.
