### ISSUE TITLE
Fail to build in VS 2015.

### ISSUE THREAD

**Issue by ccic** [Microsoft/Cognitive-Vision-Windows#23]
I opened the solution VisionAPI-WPF-Samples, but the build failed:

1>------ Build started: Project: SampleUserControlLibrary, Configuration: Debug Any CPU ------
1>C:\home\Study\Microsoft\Cognitive-Vision-Windows\Cognitive-Common-Windows\SampleUserControlLibrary\SampleUserControl.xaml(8,43,8,58): error CS0234: The type or namespace name 'SampleScenarios' does not exist in the namespace 'SampleUserControlLibrary.SampleUserControlLibrary' (are you missing an assembly reference?)
2>------ Build started: Project: VisionAPI-WPF-Samples, Configuration: Debug Any CPU ------
2>C:\home\Study\Microsoft\Cognitive-Vision-Windows\Sample-WPF\MainWindow.xaml(12,10): error MC3074: The tag 'SampleScenarios' does not exist in XML namespace 'clr-namespace:SampleUserControlLibrary;assembly=SampleUserControlLibrary'. Line 12 Position 10.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by chbuehle** [comment]
Please look at issue #8
