### ISSUE TITLE
API endpoint should be configurable

### ISSUE THREAD

**Issue by DibranMulder** [Microsoft/Cognitive-Vision-Windows#25]
The code uses the following endpoint:

> https://westcentralus.api.cognitive.microsoft.com/vision/v1.0

However I'm an European and therefore use:

> https://westeurope.api.cognitive.microsoft.com/vision/v1.0

It would be nice if you could enter the endpoint just like you do with the keys.

**Comment by cthrash** [comment]
You can, just called the overloaded constructor, shown [here](https://github.com/Microsoft/Cognitive-Vision-Windows/blob/master/ClientLibrary/VisionServiceClient.cs#L131).

**Comment by DibranMulder** [comment]
I'm talking about the Sample-WPF application, not the client library.

**Comment by cthrash** [comment]
I understand what you're asking now.

**Comment by cthrash** [comment]
This has been fixed for a while now.  Sorry for the late response
