### ISSUE TITLE
The WPF sample is missing the Control library

### ISSUE THREAD

**Issue by asipras** [Microsoft/Cognitive-Vision-Windows#29]
It looks like WPF sample build fails. The Client UI library needed to build the sample is not part of the repo. The library needs to be added as part of the repo for the WPF sample to build.

See also,
#15

**Comment by markti** [comment]
Serious omission. This library is completely broken without it!

**Comment by cthrash** [comment]
Please take a look at https://github.com/Microsoft/Cognitive-Vision-Windows/issues/8

**Comment by markti** [comment]
why even separate it out just for three user controls? is there a value?

**Comment by cthrash** [comment]
This is because the project is shared by multiple Cognitive Services SDKs.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
