### ISSUE TITLE
sample WPF won't build

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/Cognitive-Vision-Windows#31]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SampleUserControlLibrary' could not be found (are you missing a using directive or an assembly reference?)	VisionAPI-WPF-Samples	C:\Users\antho\Cognitive-Vision-Windows\Sample-WPF\MainWindow.xaml.cs	35	Active

**Comment by cthrash** [comment]
Please take a look at https://github.com/Microsoft/Cognitive-Vision-Windows/issues/8.

**Comment by amthomas46** [comment]
thanks, sorry
