### ISSUE TITLE
customized endpoint in the main window not used in wpf_sample

### ISSUE THREAD

**Issue by mydmdm** [Microsoft/Cognitive-Vision-Windows#32]
Even I set the endpoint (e.g. eastasia) in the main window, the pages still use the default (or hard-coded westcentralus). This will cause client throws exception. 
I have local fix for it, however, not sure how to create a PR.

**Comment by cthrash** [comment]
this should be addressed [here](https://github.com/Microsoft/Cognitive-Vision-Windows/pull/40)
please reactivate if you find otherwise.
