### ISSUE TITLE
Cannot Build - Missing SampleUerControlLibrary project

### ISSUE THREAD

**Issue by spartyspartan** [Microsoft/Cognitive-Vision-Windows#8]
MainPage.xaml contains a single element in side the root grid - sampleUtil:SampleScenarios  - which is in a project that is not part of the solution or repo.

**Comment by cthrash** [comment]
This repo has a submodule on which it depends.  Unfortunately, Visual Studio won't pick these up automatically, so you'll need to do this from a command prompt: `git pull --recurse-submodules` for example.

**Comment by FIVIL** [comment]
can you be a little more specific??
i downloaded project as zip file but the SampleUserControlLibrary.csproject dosent exist any where also there is no folder with this name so i cant even manually add that to the project 
it seems the file dosent exist at all

**Comment by chsienki** [comment]
If you have downloaded via zip, it wont include the git repository information, so you won't be able to init the submodule. 

You need to download the following repo: https://github.com/Microsoft/Cognitive-Common-Windows as a zip and put that as the contents of the Cognitive-Common-Windows folder at the root of this one (create it if needed).

>/Cognitive-Vision-Windows
>&nbsp;&nbsp;&nbsp;&nbsp;/ _Contents of this repo_
>&nbsp;&nbsp;&nbsp;&nbsp;/ Cognitive-Common-Windows
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/_Contents of that repo_

**Comment by FIVIL** [comment]
oh i see.
i also need to say tnx for you answer and all the great job that you guys
doing in MS
i mean this is perfect
i am really really grateful
