### ISSUE TITLE
Computer Vision API (Analyze an image) not giving proper responses for machinery

### ISSUE THREAD

**Issue by PrasenjitSaha** [Microsoft/Cognitive-Vision-Windows#9]
I have a requirement to identify machinery image like (Lathe, Miller, Shaping etc.). But Analyze Image API (https://api.projectoxford.ai/vision/v1.0/analyze) is not providing correct machinery name. Attached is the image of a Lathe Machine but it is providing 	[ { "name": "sky", "confidence": 0.985724687576294 }, { "name": "projector", "confidence": 0.1976199895143509 } ]
![analyzeimagelathemachine](https://cloud.githubusercontent.com/assets/19383204/21633931/40469776-d279-11e6-9c30-177a46a64c9c.jpg)

Also another image of "Shaping Machine" but Analyzer is providing "Miller" Machine. PFA
![analyzeshapingimage](https://cloud.githubusercontent.com/assets/19383204/21633990/c900cf00-d279-11e6-9642-be689ed19284.jpg)

Is there any way to correct an incorrect tagged image?

**Comment by Pinoplast** [comment]
How do you think, is Computer vision api trained for labeling all objects? You can try Google vision api.
Also you can use tensorFlow and train it independently.

**Comment by cthrash** [comment]
You are encountering the limitation of the API.  Depending on your use case, you may wish to explore the [Custom Vision](http://customvision.ai) product.
